compute-exponential.exe : compute-exponential.o
	gcc -g -Wall compute-exponential.o -o compute-exponential.exe
	
compute-exponential.o : compute-exponential.c
	gcc -g -Wall -c compute-exponential.c
	
clean:
	rm -f *.o *.exe *~